// automatically generated by Socialshareprivacy_XH
// do not modify directly -- instead make your modifications in "Plugin Config" and "Plugin Language"
jQuery(function() {
    jQuery('.socialshareprivacy').socialSharePrivacy({
	info_link: 'http://www.heise.de/ct/artikel/2-Klicks-fuer-mehr-Datenschutz-1333879.html',
	txt_help: 'If you activate these buttons by clicking, information will be sent to Facebook, Twitter resp. Google in the USA and perhaps stored there. For more details click on the <em>i</em>.',
	settings_perma: 'Activate permanently and approve data transmission:',
	cookie_path: '/CMSimple_XH_151/',
	cookie_domain: 'localhost',
	cookie_expires: 365,
	css_path: '',
	services: {
	    facebook: {
		status: 'on',
		dummy_img: './plugins/socialshareprivacy/css/images/dummy_facebook_en.png',
		txt_info: '2 clicks for more privacy: only after clicking the button is active and you can sent your recommendation to Facebook. As soon as you activate the button, data will be transmitted to third parties &ndash; see <em>i</em>.',
		txt_fb_off: 'not connected to Facebook',
		txt_fb_on: 'connected to Facebook',
		perma_option: 'on',
		display_name: 'Facebook',
		referrer_track: '',
		language: 'en_US', // TODO
		action: 'like'
	    },
	    twitter: {
		status: 'on',
		dummy_img: './plugins/socialshareprivacy/css/images/dummy_twitter.png',
		txt_info: '2 clicks for more privacy: only after clicking the button is active and you can sent your recommendation to Twitter. As soon as you activate the button, data will be transmitted to third parties &ndash; see <em>i</em>.',
		txt_twitter_off: 'not connected to Twitter',
		txt_twitter_on: 'connected to Twitter',
		perma_option: 'on',
		display_name: 'Twitter',
		referrer_track: '',
		language: 'en'
	    },
	    gplus: {
		status: 'on',
		dummy_img: './plugins/socialshareprivacy/css/images/dummy_gplus.png',
		txt_info: '2 clicks for more privacy: only after clicking the button is active and you can sent your recommendation to Google+. As soon as you activate the button, data will be transmitted to third parties &ndash; see <em>i</em>.',
		txt_gplus_off: 'not connected to Google+',
		txt_gplus_on: 'connected to Google+',
		perma_option: 'on',
		display_name: 'Google+',
		referrer_track: '',
		language: 'en'
	    }
	}
    })
})